#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

appIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAA3NCSVQICAjb4U/gAAAG9ElE"
    "QVRIia2WWWxcVxnHv7PdOzN37p2xPbbHHsd27PESL0mIs+KSkMgEiUIaJMSmSkEKoognHnhA"
    "qkBQBAjxUFVFooJGqpB4KSk0hDbQClJSh8SJSdI4TmzHicceb7N4ZjzL3e85PATSEHmqWOr3"
    "eI/O/6fz/b/7Pwd5niGETYgGH3Nx215jrIYKYY1fe0NiLd1d/YpSB0ABBAAHEAAyAHoCLdvz"
    "LIQQxhQAua6RXVuauHUt1hzo2/ZF6npWKmX/5rdvtzS/2x3XgoqkG5ZteZiyoT1bOtr7FUWV"
    "JD9lEiEUIywECME9z3Fd27KMYjF7+eqVmTt5gl2CkSSzctmduWcXSvpPfnTEcUt0cXHi/X8l"
    "OuP9WOClJVMvlylRBCDTQ3OJqanJsUhEBIOIMWAMY4woJbbDMcalopVatVzuI37bx7bWapi7"
    "nEmUyUpNWFpJz717/oOu+A7keeb03X/fvDm5slQwdBNjgTGSZeZ4aPZe5u9/48PDWzSV5PJF"
    "iZFQSOWcAwJM0Mpy/vKl+aAWHD5kRWobQip1LM/1gAsU1Pwd8ejwgQONDV1ICPGgj7Zdcl0b"
    "BGBCEMKua46+/+pbZ6+rasDjUc59kkQxwQjAMC3BBUI6Rslw2Dx+fFtH/HsAsus5nHsIYVlW"
    "KFUBMADQ/xklSVKdJH1onCzdEvZd27Q/9ZnZnZ/IK9pBRLoBhQAEhiKIudL6jbGx3NvnQtnU"
    "RE/PDUSflh43Hx4FPFbJOzd/+eJL9M508+hocPtgbs/uM/E4CoeYEJDL8+lpNDau3L4dNfRg"
    "NuvFYr9v7+pHuP3JAZVMJpdKt1JilCv0wsW68xfCksTDYUkIKBRs18UYE0owpWJpOVBYX0fI"
    "3VCoGqBnx87dPd2TY1dUBMIn4/0HBg4M9+/c2SWEGB+feuevVycn5xECztGO7bme3mFA8U0B"
    "kBba2RW/cnlMRQBciIHBrd967hhjDAB6erckF1ITEwlMAED09ph+ZaCKDuBqC4iENY0DEoCQ"
    "43h/PnNxdWXtwZJp2pqmYIQAAGPQNIRwqJpOtRMACNu2kOAAGIQQzbFIJluoqdUAQGJsW1/7"
    "gxDhHCwTQNjVMqUqwLFXLYv096GpO0AInrh5/8SzPzt8ZJdt2fl8+eChHQghIUBVXdvxXDdD"
    "NxzSjwAU1+8V1tWjRxtnZxO2gwzD0XX7zT+NCiF8PimZzAAAF7Bnl+46SC/PabUb61TzoLS8"
    "NH/rtnZ/rkjpg2QVqupTFJ+mBRBCCwtpIYQs8aaoe/FybTYzB2Bs6gT55KKezqg+ab2xAc/e"
    "dwe3tz337S+MX52qrw+HQsFfvfzm6mqhvsnzPHR/XllZLXb0lAD8Tw4wSyVuWcQ0jZaWUrG8"
    "5ccvnNy7r2/XUG8g4ItEQpSxHzz/2ta28tKy3zJJpewBWJtqEWEMEIJ0xoo2rj/11ODefX0A"
    "vLU1GomEQcDnnt7f29sUa3LmEhIhQBkCIJtqkdZQz3yys7Lq798mVtLmSy/+wXVzkuSbX6gY"
    "utHW1hhUcDJBM1karnUidTKAsilAeOvWxqboWmLef/6fzYnElbNnLyMkAIBzAACEEKMYI4Vz"
    "3NpSisW6AdRNtYhFY8NHPp22bZRIyFwAIRhjgjGhlFBKCMFcgMcRId7RkfWayP5qUlWjgkgj"
    "X/9a8+6hlOuC4Bv8ppwjLuDgweyx43FMP1lN5+GNtmFNzd5+4dSry/94T11J+QAAPYgHARiJ"
    "1hZrZKRy4kRHW+f3Ed44SjcEeACuEJ5llSuVoq5PS/i99Ors6dOZP56pKxQkAGiot778pbWR"
    "EdbWcVgLf0WSOwFItWY8BIhM5u6ND64vzK9UyrphmOWSk0xmLCd/5EjnN09+xzXPvXPu9Z/+"
    "QgkEvB8+D9sGh1773VQyqUQi0aamOllmTJJr62ri8Y72tj5CPjT8v1M0PTP6yqnztlkX9GuR"
    "2milXAqq/tb2q5O3Vu/dzecKFb/vmcNHfZLv1wG/tGvfd5PLoRvXbyOc7+joTK02GIZR1t1S"
    "ZWk5de2ZYy0nnv1qwN/4KEAEAqw7rqRTaiG3xDkKBu1wjWQ7bDEZzabXT37j5wE/6+pp1tSh"
    "5EL+5Vfe0nVrLUsprRsYKDBGKGN19apuhFLZgqI4jl2C/wegaLSrPnKhqZEP9B2qjzRLsl+W"
    "pVOnXk+nbjgO4zOmx/VypWn79qGZu7PjV6cJwRTLoRqye+++/fsO6EbF0EuLi4vMJ3fHm0Oh"
    "zsc9sJ2c6xQDgdZHvbp06S9vnB7NrxVNy3RdLkk0pAVsx3FdVwn6wmElFot8/thnW2KDD7fY"
    "Tq5cSoTDfRj7qk3Ro+V4nu66tue5QnAhBAiBCSGEESIRwhBiAHSjB7J4+PGjAR9D/QevpkOk"
    "f7H8iAAAAABJRU5ErkJggg==")

